# Generated by Django 4.2 on 2023-05-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllegroTracker', '0002_alter_product_options_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minutes_refresh_rate',
            field=models.IntegerField(default=1),
        ),
    ]
