# Generated by Django 4.2 on 2023-05-17 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllegroTracker', '0003_product_minutes_refresh_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minutes_refresh_rate',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
