# Generated by Django 4.2 on 2023-05-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllegroTracker', '0004_alter_product_minutes_refresh_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
