# Generated by Django 4.1.5 on 2023-05-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllegroTracker', '0005_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='target_price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
